name: tp2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  app_color: ^1.0.3
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  go_router: ^14.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
